import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";

// The board enters a short pairing code (generated by a parent in the web
// app) exactly once; in exchange it receives a long-lived device token.
export async function POST(req: NextRequest) {
  const { code } = (await req.json()) as { code?: string };
  if (!code) return NextResponse.json({ error: "Missing code" }, { status: 400 });

  const admin = createAdminClient();
  const { data: pairing } = await admin
    .from("pairing_codes")
    .select("*")
    .eq("code", code.trim().toUpperCase())
    .eq("used", false)
    .gt("expires_at", new Date().toISOString())
    .maybeSingle();

  if (!pairing) {
    return NextResponse.json({ error: "Invalid or expired code" }, { status: 401 });
  }

  const { data: board, error } = await admin
    .from("boards")
    .insert({ family_id: pairing.family_id })
    .select("token")
    .single();
  if (error || !board) {
    return NextResponse.json({ error: "Pairing failed" }, { status: 500 });
  }

  // Demo codes (10-year expiry) stay reusable; real codes are single-use.
  const longLived =
    new Date(pairing.expires_at).getTime() - Date.now() > 1000 * 60 * 60 * 24 * 30;
  if (!longLived) {
    await admin.from("pairing_codes").update({ used: true }).eq("code", pairing.code);
  }

  return NextResponse.json({ token: board.token });
}
