import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { clientIp, rateLimit } from "@/lib/rateLimit";

// The board enters a short pairing code (generated by a parent in the web
// app) exactly once; in exchange it receives a long-lived device token.
export async function POST(req: NextRequest) {
  // Defense-in-depth against brute-forcing the code space. A real board pairs
  // in one or two tries; 10 attempts per 10 minutes is generous for typos.
  const limit = rateLimit(`pair:${clientIp(req)}`, {
    max: 10,
    windowMs: 10 * 60 * 1000,
    blockMs: 15 * 60 * 1000,
  });
  if (!limit.ok) {
    return NextResponse.json(
      { error: "Too many attempts — try again in a few minutes." },
      { status: 429, headers: { "Retry-After": String(limit.retryAfterSeconds) } }
    );
  }

  const { code } = (await req.json()) as { code?: string };
  if (!code) return NextResponse.json({ error: "Missing code" }, { status: 400 });

  const admin = createAdminClient();
  const { data: pairing } = await admin
    .from("pairing_codes")
    .select("*")
    .eq("code", code.trim().toUpperCase())
    .eq("used", false)
    .gt("expires_at", new Date().toISOString())
    .maybeSingle();

  if (!pairing) {
    return NextResponse.json({ error: "Invalid or expired code" }, { status: 401 });
  }

  const { data: board, error } = await admin
    .from("boards")
    .insert({ family_id: pairing.family_id })
    .select("token")
    .single();
  if (error || !board) {
    return NextResponse.json({ error: "Pairing failed" }, { status: 500 });
  }

  // Every code is single-use, no exceptions — a code that lingered as reusable
  // would be a permanent pairing key for anyone who learned it.
  await admin.from("pairing_codes").update({ used: true }).eq("code", pairing.code);

  return NextResponse.json({ token: board.token });
}
